# Generated by Django 4.2.7 on 2023-11-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '正常')], verbose_name='状态')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='上次登陆时间')),
            ],
        ),
        migrations.CreateModel(
            name='PlatFormDouYin',
            fields=[
                ('access_token', models.CharField(max_length=64, verbose_name='client_token 接口调用凭证')),
                ('refresh_token', models.CharField(max_length=64, verbose_name='refresh_token')),
                ('status', models.SmallIntegerField(choices=[(0, '过期'), (1, '有效')], verbose_name='状态')),
                ('open_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='open_id')),
                ('expires_in', models.DateTimeField(verbose_name='过期时间')),
                ('e_account_role', models.CharField(max_length=32, null=True, verbose_name='企业号类型')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('avatar', models.CharField(max_length=64, verbose_name='头像')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
