# Generated by Django 4.2.7 on 2023-11-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='上次登陆时间')),
            ],
        ),
        migrations.CreateModel(
            name='PlatFormDouYin',
            fields=[
                ('access_token', models.CharField(max_length=255, verbose_name='client_token 接口调用凭证')),
                ('refresh_token', models.CharField(max_length=64, verbose_name='refresh_token')),
                ('open_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='open_id')),
                ('expires_in', models.DateTimeField(verbose_name='过期时间')),
                ('e_account_role', models.CharField(max_length=255, null=True, verbose_name='企业号类型')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataDouYin',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='作品ID')),
                ('title', models.CharField(max_length=255, verbose_name='作品标题')),
                ('video_status', models.SmallIntegerField(choices=[(1, '已发布'), (2, '不适宜公开'), (4, '审核中')], default=1, verbose_name='视频状态')),
                ('create_time', models.CharField(max_length=64, verbose_name='创建时间')),
                ('media_type', models.SmallIntegerField(choices=[(2, '图集'), (4, '视频')], default=4, verbose_name='媒体类型')),
                ('cover', models.CharField(max_length=500, verbose_name='封面')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('share_url', models.CharField(max_length=500, verbose_name='分享url')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载数')),
                ('forward_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('open_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.platformdouyin', verbose_name='open_id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
