# Generated by Django 4.2.7 on 2023-11-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdouyin',
            name='avatar',
            field=models.CharField(max_length=255, verbose_name='头像'),
        ),
    ]
