# Generated by Django 4.2.7 on 2023-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdouyin',
            name='auth_time',
            field=models.DateTimeField(null='1995-12-15 06:15:00', verbose_name='授权时间'),
            preserve_default='1995-12-15 06:15:00',
        ),
    ]
