# Generated by Django 4.2.7 on 2023-11-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_platformdouyin_auth_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatFormZhiHu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=26, verbose_name='昵称')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
                ('expires_time', models.DateTimeField(verbose_name='过期时间')),
                ('auth_time', models.DateTimeField(null='1995-12-15 06:15:00', verbose_name='授权时间')),
                ('zh_uid', models.BigIntegerField(verbose_name='知乎用户ID')),
                ('z_c0', models.CharField(max_length=500, verbose_name='cookies')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
