# Generated by Django 4.2.7 on 2023-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdouyin',
            name='access_token',
            field=models.CharField(max_length=255, verbose_name='client_token 接口调用凭证'),
        ),
        migrations.AlterField(
            model_name='platformdouyin',
            name='e_account_role',
            field=models.CharField(max_length=255, null=True, verbose_name='企业号类型'),
        ),
    ]
