# Generated by Django 4.2.7 on 2023-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_remove_platformzhihu_id_alter_platformzhihu_zh_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformzhihu',
            name='zh_uid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='知乎用户ID'),
        ),
    ]
