# Generated by Django 4.2.7 on 2023-11-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_platformzhihu_zh_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformzhihu',
            name='z_c0',
            field=models.CharField(max_length=500, verbose_name='授权cookies'),
        ),
        migrations.CreateModel(
            name='DataZhiHu',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='作品ID')),
                ('title', models.CharField(max_length=255, verbose_name='作品标题')),
                ('like_count', models.IntegerField(verbose_name='点赞数')),
                ('comment_count', models.IntegerField(verbose_name='评论数')),
                ('play_count', models.IntegerField(verbose_name='播放数')),
                ('vote_up_count', models.IntegerField(verbose_name='赞同数')),
                ('share_url', models.CharField(max_length=500, verbose_name='分享url')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
                ('zh_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.platformzhihu', verbose_name='知乎用户ID')),
            ],
        ),
    ]
