# Generated by Django 4.2.7 on 2023-11-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_platformdouyin_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdouyin',
            name='open_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='open_id'),
        ),
        migrations.CreateModel(
            name='DataDouYin',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='作品ID')),
                ('title', models.CharField(max_length=255, verbose_name='作品标题')),
                ('video_status', models.SmallIntegerField(choices=[(1, '已发布'), (2, '不适宜公开'), (4, '审核中')], default=1, verbose_name='视频状态')),
                ('create_time', models.CharField(max_length=64, verbose_name='创建时间')),
                ('media_type', models.SmallIntegerField(choices=[(2, '图集'), (4, '视频')], default=4, verbose_name='媒体类型')),
                ('cover', models.CharField(max_length=255, verbose_name='封面')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('share_url', models.CharField(max_length=255, verbose_name='分享url')),
                ('comment_count', models.IntegerField(default=0, max_length=32, verbose_name='评论数')),
                ('digg_count', models.IntegerField(default=0, max_length=32, verbose_name='点赞数')),
                ('download_count', models.IntegerField(default=0, max_length=32, verbose_name='下载数')),
                ('forward_count', models.IntegerField(default=0, max_length=32, verbose_name='收藏数')),
                ('play_count', models.IntegerField(default=0, max_length=32, verbose_name='播放数')),
                ('share_count', models.IntegerField(default=0, max_length=32, verbose_name='分享数')),
                ('open_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.platformdouyin', verbose_name='open_id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
