# Generated by Django 4.2.7 on 2023-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_platformdouyin_open_id_datadouyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadouyin',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='datadouyin',
            name='digg_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='datadouyin',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='下载数'),
        ),
        migrations.AlterField(
            model_name='datadouyin',
            name='forward_count',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='datadouyin',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='播放数'),
        ),
        migrations.AlterField(
            model_name='datadouyin',
            name='share_count',
            field=models.IntegerField(default=0, verbose_name='分享数'),
        ),
    ]
