# Generated by Django 4.2.7 on 2023-11-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_platformzhihu_z_c0_datazhihu'),
    ]

    operations = [
        migrations.AddField(
            model_name='datazhihu',
            name='create_time',
            field=models.CharField(default=1968, max_length=64, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
