# Generated by Django 4.2.7 on 2023-11-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_alter_datadouyin_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadouyin',
            name='cover',
            field=models.CharField(max_length=500, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='datadouyin',
            name='share_url',
            field=models.CharField(max_length=500, verbose_name='分享url'),
        ),
    ]
