# Generated by Django 4.2.7 on 2023-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_datazhihu_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='datazhihu',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '文章'), (4, '视频')], default=4, verbose_name='作品类型'),
            preserve_default=False,
        ),
    ]
