# Generated by Django 4.2.7 on 2023-11-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_datazhihu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatFormBaiJiaHao',
            fields=[
                ('nickname', models.CharField(max_length=26, verbose_name='昵称')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
                ('expires_time', models.DateTimeField(verbose_name='过期时间')),
                ('auth_time', models.DateTimeField(null='1995-12-15 06:15:00', verbose_name='授权时间')),
                ('app_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='百家号用户ID')),
                ('bduss', models.CharField(max_length=500, verbose_name='授权cookies')),
                ('token', models.CharField(max_length=500, verbose_name='授权token')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
