# Generated by Django 4.2.7 on 2023-12-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_platformbaijiahao_bjhstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatFormData',
            fields=[
                ('platform', models.SmallIntegerField(choices=[(0, '未知'), (1, '抖音'), (2, '知乎'), (3, '百家号')], default=0, verbose_name='平台名称')),
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='作品ID')),
                ('title', models.CharField(max_length=255, verbose_name='作品标题')),
                ('type', models.CharField(max_length=64, verbose_name='作品类型')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='数据更新时间')),
                ('platform_uid', models.CharField(max_length=500, verbose_name='平台用ID')),
                ('share_url', models.CharField(max_length=500, verbose_name='分享链接')),
                ('like_count', models.IntegerField(verbose_name='点赞数')),
                ('comment_count', models.IntegerField(verbose_name='评论数')),
                ('play_count', models.IntegerField(verbose_name='播放数')),
                ('download_rec_count', models.IntegerField(verbose_name='下载数/推荐数')),
                ('share_vote_count', models.IntegerField(verbose_name='分享数/赞同数')),
                ('forward_collect_count', models.IntegerField(verbose_name='转发数/收藏数')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
