# Generated by Django 4.2.7 on 2023-12-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_platformdata_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdata',
            name='item_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='作品ID'),
        ),
    ]
