# Generated by Django 4.2.7 on 2023-12-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_remove_datazhihu_uid_remove_datazhihu_zh_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='时间')),
                ('nickname', models.CharField(max_length=64, verbose_name='用户名')),
                ('platform_uid', models.CharField(max_length=500, verbose_name='平台用ID')),
                ('uid', models.CharField(max_length=64, verbose_name='用户ID')),
                ('platform', models.CharField(max_length=64, verbose_name='平台')),
                ('like_sum', models.IntegerField(verbose_name='点赞数')),
                ('comment_sum', models.IntegerField(verbose_name='评论数')),
                ('play_sum', models.IntegerField(verbose_name='播放数')),
                ('download_rec_sum', models.IntegerField(verbose_name='下载数/推荐数')),
                ('share_vote_sum', models.IntegerField(verbose_name='分享数/赞同数')),
                ('forward_collect_sum', models.IntegerField(verbose_name='转发数/收藏数')),
            ],
        ),
    ]
