# Generated by Django 4.2.7 on 2023-12-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_historydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatFormBilibili',
            fields=[
                ('openid', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='openid')),
                ('access_token', models.CharField(max_length=255, verbose_name='access_token')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='refresh_token')),
                ('nickname', models.CharField(max_length=64, verbose_name='用户名')),
                ('avatar', models.CharField(max_length=255, verbose_name='头像')),
                ('expires_in', models.DateTimeField(verbose_name='过期时间')),
                ('auth_time', models.DateTimeField(null='1995-12-15 06:15:00', verbose_name='授权时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
