# Generated by Django 4.2.7 on 2023-12-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_platformbilibili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdata',
            name='platform',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '抖音'), (2, '知乎'), (3, '百家号'), (4, '哔哩哔哩')], default=0, verbose_name='平台名称'),
        ),
        migrations.CreateModel(
            name='SensitiveWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.SmallIntegerField(verbose_name='分组')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('words', models.CharField(max_length=2000, verbose_name='敏感词')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user', verbose_name='用户ID')),
            ],
        ),
    ]
